[package]
name = "revault-gui"
version = "0.0.1"
readme = "README.md"
description = "Revault GUI"
repository = "https://github.com/re-vault/revault-gui"
license = "BSD-3-Clause"
authors = ["Edouard Paris <m@edouard.paris>"]
edition = "2018"

[dependencies]
iced = { version = "0.2", features = ["tokio", "wgpu", "svg", "debug"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

log = "0.4"
fern = "0.5"
chrono = "0.4"

dirs = "3.0.1"
toml = "0.5"

rust-embed = "5.6.0"

[target.'cfg(windows)'.dependencies]
uds_windows = "0.1.5"
