[package]
name = "revault-gui"
version = "0.1.0"
authors = ["Edouard Paris <m@edouard.paris>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.2", features = ["svg"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

log = "0.4"
fern = "0.5"
chrono = "0.4"

dirs = "3.0.1"
toml = "0.5"

rust-embed = "5.6.0"

[target.'cfg(windows)'.dependencies]
uds_windows = "0.1.5"
